"""add caller_phone to calls

Revision ID: a81c555e193c
Revises: 575c90a3e2e2
Create Date: 2026-03-04 15:37:16.804600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81c555e193c'
down_revision: Union[str, None] = '575c90a3e2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('caller_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'caller_phone')
    # ### end Alembic commands ###
